# key? 32byte (256bit)??
jwt:
  secretKey: 9f7c3d2e1b0a5f6e8c7d4a1b6e9f2c3d
  refreshKey: 9f7c3d2e1b0a5f6e8c7d4a1b6e9f2c3d

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect



